Models/ErrorViewModel.cs
namespace CruzKITELEC1C.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Instructor.cs
namespace CruzKITELEC1C.Models
{
    public enum Rank
    {
        Instructor, AssistantProfessor, AssociateProfessor, Professor
    }
    public class Instructor
    {
        public int InstructorId { get; set; }
        public string InstructorFirstName { get; set; }
        public string InstructorLastName { get; set; }
        public bool IsTenured { get; set; }
        public DateTime HiringDate { get; set; }
        public Rank Rank { get; set; }
    }
}

Models/Student.cs
using System.ComponentModel.DataAnnotations;

namespace CruzKITELEC1C.Models
{
    public enum Course
    {
        BSIT, BSCS, BSIS, OTHER
    }

    public class Student
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public double GPA { get; set; }
        public Course Course { get; set; }
        public DateTime AdmissionDate { get; set; }
        public string Email { get; set; }
    }
}

Controllers/HomeController.cs
using CruzKITELEC1C.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CruzKITELEC1C.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using CruzKITELEC1C.Models;
namespace CruzKITELEC1C.Controllers
{
    public class InstructorController : Controller
    {
        List<Instructor> InstructorsList = new List<Instructor>()
        {
            new Instructor()
            {
                InstructorId = 1,
                InstructorFirstName = "Gabriel", InstructorLastName = "Montano", HiringDate = DateTime.Now,
                IsTenured = true, Rank = Rank.Instructor
            },
            new Instructor()
            {
                InstructorId = 2,
                InstructorFirstName = "Leo", InstructorLastName = "Lintag", HiringDate = DateTime.Parse("25/2/2000").Date,
                IsTenured = true, Rank = Rank.AssistantProfessor
            },
            new Instructor()
            {
                InstructorId = 3,
                InstructorFirstName = "Amado", InstructorLastName = "Sapit",  HiringDate = DateTime.Parse("25/3/2000").Date,
                IsTenured = false, Rank = Rank.AssociateProfessor
            },
            new Instructor()
            {
                InstructorId = 4,
                InstructorFirstName = "Bernard", InstructorLastName = "Sanidad", HiringDate = DateTime.Parse("1/1/2015").Date,
                IsTenured = false, Rank = Rank.Professor
            }

        };
        public IActionResult Index()
        {
            return View(InstructorsList);
        }

        public IActionResult ShowDetails(int id)
        {


            Instructor instructor = InstructorsList.FirstOrDefault(t => t.InstructorId == id);
            if (instructor != null)
            {
                return View(instructor);
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult AddInstructor()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddInstructor(Instructor newInstructor)
        {
            InstructorsList.Add(newInstructor);
            return View("Index", InstructorsList);
        }

        [HttpGet]
        public IActionResult UpdateInstructor(int id)
        {
            Instructor? instructor = InstructorsList.FirstOrDefault(t => t.InstructorId == id);

            if (instructor != null)
                return View(instructor);

            return NotFound();
        }

        [HttpPost]
        public IActionResult UpdateInstructor(Instructor instructorChanges)
        {
            Instructor? instructor = InstructorsList.FirstOrDefault(t => t.InstructorId == instructorChanges.InstructorId);
            if (instructor != null)
            {
                instructor.InstructorFirstName = instructorChanges.InstructorFirstName;
                instructor.InstructorLastName = instructorChanges.InstructorLastName;
                instructor.Rank = instructorChanges.Rank;
                instructor.HiringDate = instructorChanges.HiringDate;
            }
            return View("Index", InstructorsList);
        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using CruzKITELEC1C.Models;

namespace CruzKITELEC1C.Controllers
{
    public class StudentController : Controller
    {
        List<Student> StudentList = new List<Student>
            {
                new Student()
                {
                    Id= 1,FirstName = "Kyla", LastName = "Cruz",
                    Course = Course.BSIT, AdmissionDate = DateTime.Parse("2021-08-26"),
                    GPA = 1.5, Email = "kylamarielle.cruz.cics@ust.edu.ph"
                },
                new Student()
                {
                    Id= 2,FirstName = "Joshua",LastName = "Garcia",
                    Course = Course.BSIS, AdmissionDate = DateTime.Parse("2022-08-07"),
                    GPA = 1, Email = "joshua.garcia.cics@ust.edu.ph"
                },
                new Student()
                {
                    Id= 3,FirstName = "David",LastName = "Licauco",
                    Course = Course.BSCS, AdmissionDate = DateTime.Parse("2020-01-25"),
                    GPA = 1.5, Email = "david.licauco.cics@ust.edu.ph"
                },
                new Student()
                {
                    Id= 4,FirstName = "Neil",LastName = "Gallego",
                    Course = Course.OTHER, AdmissionDate = DateTime.Parse("2021-08-09"),
                    GPA = 1, Email = "neil.gallego.cics@ust.edu.ph"
                }
            };
        public IActionResult Index()
        {

            return View(StudentList);
        }

        public IActionResult ShowDetails(int id)
        {
            //Search for the student whose id matches the given id
            Student? student = StudentList.FirstOrDefault(st => st.Id == id);

            if (student != null)//was an student found?
                return View(student);

            return NotFound();
        }

        [HttpGet]
        public IActionResult AddStudent()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddStudent(Student newStudent)
        {
            StudentList.Add(newStudent);
            return View("Index", StudentList);
        }

        [HttpGet]
        public IActionResult UpdateStudent(int id)
        {
            //Search for the student whose id matches the given id
            Student? student = StudentList.FirstOrDefault(st => st.Id == id);

            if (student != null)//was an student found?
                return View(student);

            return NotFound();
        }

        [HttpPost]
        public IActionResult UpdateStudent(Student studentChanges)
        {
            Student? student = StudentList.FirstOrDefault(st => st.Id == studentChanges.Id);
            if(student != null)
            {
                student.FirstName = studentChanges.FirstName;
                student.LastName = studentChanges.LastName;
                student.Email = studentChanges.Email;
                student.Course = studentChanges.Course;
                student.AdmissionDate = studentChanges.AdmissionDate;
                student.GPA = studentChanges.GPA;
            }
            return View("Index", StudentList);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Instructor/AddInstructor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Instructor;

<h1>Instructor Form</h1>


<form asp-action="AddInstructor" asp-controller="Instructor" method="post">
    <div class="form-group row">
        <label asp-for="InstructorId" class="col-sm-2 col-form-label">ID</label>
        <div class="col-sm-10">
            <input asp-for="InstructorId" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="InstructorFirstName" class="col-sm-2 col-form-label">Firstname</label>
        <div class="col-sm-10">
            <input asp-for="InstructorFirstName" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="InstructorLastName" class="col-sm-2 col-form-label">Lastname:</label>
        <div class="col-sm-10">
            <input asp-for="InstructorLastName" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Rank" class="col-sm-2 col-form-label">Rank:</label>
        <div class="col-sm-10">
            <select asp-for="Rank" asp-items="@Html.GetEnumSelectList(typeof(Rank))" class="form-control" class="form-control"></select><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="HiringDate" class="col-sm-2 col-form-label">Hiring Date:</label>
        <div class="col-sm-10">
            <input asp-for="HiringDate" class="form-control"><br />
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

Views/Instructor/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<CruzKITELEC1C.Models.Instructor>
@{    
}
<h1>Instructor List</h1>
<a class="btn btn-primary" asp-action="AddInstructor">Add Instructor</a>

<div>
<table class="table table-light">
    
    <tr>
        <th>ID</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Rank</th>
        <th>Hiring Date</th>
        <th>Status</th>
        <th>Show Details</th>
        <th>Update</th>
    </tr>
    @{
        foreach(var inst in Model)
        {
            <tr>
                <td>@inst.InstructorId</td>
                <td>@inst.InstructorFirstName</td>
                <td>@inst.InstructorLastName</td>
                <td>@inst.Rank</td>
                <td>@inst.HiringDate</td>
                <td>@{
                        if(inst.IsTenured == true)
                        {
                            <span>Full-Time</span>
                        }
                        else
                        {
                            <span>Part-Time</span>
                        }
                    }
                </td>
                <td><a class="btn btn-primary" asp-action="ShowDetails" asp-route-id="@inst.InstructorId">Show Details</a></td>
                <td><a class="btn btn-primary" asp-action="UpdateInstructor" asp-route-id="@inst.InstructorId">Update</a></td>
            </tr>
        }
    }   
</table>
</div>

Views/Instructor/ShowDetails.cshtml
@model Instructor;

<h1>Show Details</h1>
<div>
<table class="table table-light">
    <tr>
        <th>ID</th>
        <td>@Model.InstructorId</td>
     </tr>

      <tr>
        <th>Firstname</th>
        <td>@Model.InstructorFirstName</td>
     </tr>
     <tr>
        <th>Lastname</th>
        <td>@Model.InstructorLastName</td>
     </tr>
     <tr>
         <th>Rank</th>
         <td>@Model.Rank</td>
     </tr>
     <tr>
         <th>Hiring Date</th>
         <td>
                @{
                    var DateHired = Model.HiringDate;
                    string HiringDate = String.Format("{0:dd/MM/yyyy}", DateHired);
                }
                @HiringDate
         </td>
     </tr>
     <tr>
        <th>Status</th>
        <td>
            @{
                if (@Model.IsTenured == true)
                {
                    <span>Full-Time</span>
                }
                else
                {
                    <span>Part-Time</span>
                }
            }
        </td>
     </tr>
</table>
</div>
<a class="btn btn-primary" asp-action="Index">Back</a>

Views/Instructor/UpdateInstructor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Instructor;

<h1>Update Instructor</h1>


<form asp-action="UpdateInstructor" asp-controller="Instructor" method="post">
    <div class="form-group row">
        <label asp-for="InstructorId" class="col-sm-2 col-form-label" hidden>ID</label>
        <div class="col-sm-10">
            <input asp-for="InstructorId" class="form-control" hidden><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="InstructorFirstName" class="col-sm-2 col-form-label">Firstname</label>
        <div class="col-sm-10">
            <input asp-for="InstructorFirstName" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="InstructorLastName" class="col-sm-2 col-form-label">Lastname:</label>
        <div class="col-sm-10">
            <input asp-for="InstructorLastName" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Rank" class="col-sm-2 col-form-label">Rank:</label>
        <div class="col-sm-10">
            <select asp-for="Rank" asp-items="@Html.GetEnumSelectList(typeof(Rank))" class="form-control" class="form-control"></select><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="HiringDate" class="col-sm-2 col-form-label">Hiring Date:</label>
        <div class="col-sm-10">
            <input asp-for="HiringDate" class="form-control"><br />
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
    <button type="button" onClick="history.back()" class="btn btn-primary">Cancel</button>
</form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CruzKITELEC1C</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CruzKITELEC1C.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CruzKITELEC1C</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructor List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CruzKITELEC1C - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/AddStudent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Student;

<h1>Student Form</h1>


<form asp-action="AddStudent" asp-controller="Student" method="post">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label">ID</label>
        <div class="col-sm-10">
            <input asp-for="Id" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="FirstName" class="col-sm-2 col-form-label">Firstname</label>
        <div class="col-sm-10">
            <input asp-for="FirstName" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="LastName" class="col-sm-2 col-form-label">Lastname:</label>
        <div class="col-sm-10">
            <input asp-for="LastName" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label">Email:</label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Course" class="col-sm-2 col-form-label">Course:</label>
        <div class="col-sm-10">
            <select asp-for="Course" asp-items="@Html.GetEnumSelectList(typeof(Course))" class="form-control" class="form-control"></select><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="AdmissionDate" class="col-sm-2 col-form-label">Date Enrolled:</label>
        <div class="col-sm-10">
            <input asp-for="AdmissionDate" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="GPA" class="col-sm-2 col-form-label">GPA:</label>
        <div class="col-sm-10">
            <input asp-for="GPA" class="form-control"><br />
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form> 
</div>

Views/Student/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Student List</h1>
<a class="btn btn-primary" asp-action="AddStudent">Add Student</a>

<table class="table table-light">
    <tr>
        <td>Name</td>
        <td>Course</td>
        <td>Date Enrolled</td>
        <td>Email</td>
        <td>GPA</td>
        <td>Details</td>
        <td>Update</td>
    </tr>
    @foreach (var student in Model)
    {
        <tr>
            <td>@student.FirstName @student.LastName</td>
            <td>@student.Course</td>
            <td>@student.AdmissionDate</td>
            <td>@student.Email</td>
            <td>@student.GPA</td>
            <td><a class="btn btn-primary" asp-action="ShowDetails" asp-route-id="@student.Id">Show Details</a></td>
            <td><a class="btn btn-primary" asp-action="UpdateStudent" asp-route-id="@student.Id">Update</a></td>
        </tr>
    }
</table>

Views/Student/ShowDetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Student;

<h1>Student Details</h1>

<table class="table table-light">
    <tr>
        <th>Id</th>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <th>Last Name</th>
        <td>@Model.LastName</td>
    </tr>
    <tr>
        <th>First Name</th>
        <td>@Model.FirstName</td>
    </tr>
    <tr>
        <th>Course</th>
        <td>@Model.Course</td>
    </tr>
    <tr>
        <th>Email</th>
        <td>@Model.Email</td>
    </tr>
    <tr>
        <th>Admission Date</th>
        <td>@Model.AdmissionDate</td>
    </tr>
    <tr>
        <th>GPA</th>
        <td>@Model.GPA</td>
    </tr>
</table>
<a class="btn btn-primary" asp-action="Index">Back</a>

Views/Student/UpdateStudent.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Student;

<h1>Update Student</h1>


<form asp-action="UpdateStudent" asp-controller="Student" method="post">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label" hidden>ID</label>
        <div class="col-sm-10">
            <input asp-for="Id" class="form-control" hidden><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="FirstName" class="col-sm-2 col-form-label">Firstname</label>
        <div class="col-sm-10">
            <input asp-for="FirstName" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="LastName" class="col-sm-2 col-form-label">Lastname:</label>
        <div class="col-sm-10">
            <input asp-for="LastName" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label">Email:</label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Course" class="col-sm-2 col-form-label">Course:</label>
        <div class="col-sm-10">
            <select asp-for="Course" asp-items="@Html.GetEnumSelectList(typeof(Course))" class="form-control" class="form-control"></select><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="AdmissionDate" class="col-sm-2 col-form-label">Date Enrolled:</label>
        <div class="col-sm-10">
            <input asp-for="AdmissionDate" class="form-control"><br />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="GPA" class="col-sm-2 col-form-label">GPA:</label>
        <div class="col-sm-10">
            <input asp-for="GPA" class="form-control"><br />
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
    <button type="button" onClick="history.back()" class="btn btn-primary">Cancel</button>
</form>
</div>